GET http://localhost:3000/api/v1/items

###

GET http://localhost:3000/api/v1/items/3

###

POST http://localhost:3000/api/v1/items HTTP/1.1
Content-Type: application/json

{
  "name": "Desk chair",
  "quantity": 3,
  "location_id": 1,
  "purchase_price": 300,
  "purchase_date": "2025-07-07 10:00:00",
  "receipt": null,
  "freeText": "Office equipment"
}

###

PUT http://localhost:3000/api/v1/items/3 HTTP/1.1
Content-Type: application/json

{
  "receipt": "89504E470D0A1A0A"
}

###
