// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table items {
  id integer [primary key]
  name varchar [not null]
  quantity integer [not null]
  location_id integer [ref: > locations.id]
  purchase_price integer
  purchase_date timestamp
  receipt blob
  freeText varchar
}

Table locations {
  id integer [primary key]
  name varchar [not null]
  parent_id integer [ref: - locations.id]
  description varchar
}

Table tags {
  id integer [primary key]
  name varchar [not null]
}

Table item_tags {
  item_id integer [primary key, ref: - items.id]
  tag_id integer [primary key, ref: - tags.id]
}

Table users {
  id integer [primary key]
  name varchar [not null]
  email varchar [not null, unique]
  role varchar [not null, ref: - roles.id]
}

Table roles {
  id integer [primary key]
  role varchar [not null]
}

Table sessions {
  id integer [primary key]
  token varchar [not null]
  expires_at timestamp [not null]
  user_id integer [ref: - users.id]
}
